### PR TITLE
Smart, semantic exception handling for image resizing. refs #3379

### PR DESCRIPTION
**Pull request by whatisjasongoldstein**
Attempt 2.

### CODE REVIEW

**Comment by Refefer** [comment]
Cleaner.  One change I notice is that it's not longer possible to opt-out of dynamic resizing for a Rich Text field.  There might be some cases where it might be beneficial to disable it (hypothetically at least, I can't think of any off the top of my head).

**Comment by whatisjasongoldstein** [comment]
I can that being useful, although it'd be better if we discovered the cases and did it automatically.

Either way it's a new bug.

**Comment by fdintino** [comment]
I like that suggestion and added Ticket #7 to address it.

**Comment by Refefer** [comment]
No need to regex the exception, just look at e.errno to give you the exact IO reason.  Much more exact and correct

**Comment by fdintino** [comment]
Did not know that. Indeed that is better. It should be written

``` python
try:
    new_image.save(new_path, **image_params)
except IOError as e:
    if e.errno != 2:
        raise e
    msg = u"There was a problem resizing this image: Could not find file: %s" \
                % os.path.split(e.filename)
    raise ImageResizeError(msg), None, sys.exc_info()[2]
```

**Comment by fdintino** [comment]
Give me a heads up when you're done so I can squash the commits.

**Comment by Refefer** [comment]
One final level of cleanness:

```
try:
    new_image.save(new_path, **image_params)
except IOError as e:
    import errno
    if e.errno != errno.ENOENT:
        raise e
    msg = u"There was a problem resizing this image: Could not find file: %s" \
                % os.path.split(e.filename)
    raise ImageResizeError(msg), None, sys.exc_info()[2]
```

**Comment by fdintino** [comment]
I was wondering where to find that constant. Damn python docs.

**Comment by whatisjasongoldstein** [comment]
Now we're just getting ridiciulous...

+1 including the error message in the message to the user.
-1 making special cases for each message.

**Comment by fdintino** [comment]
Why? It goes back to the reason we created this system... that we don't want to prevent them from saving work if, for instance, a partition is full (which would be an IOError here) or there is some other problem outside of their control.

**Comment by fdintino** [comment]
To rattle off other errors that could be triggered here that we would want to log and forget resizing, rather than bother the user:
- Out of memory
- Permission denied
- Too many open files
- Read-only filesystem
- NFS issues

**Pull request merged**
