### PR TITLE
Handle JSON parse errors for parsing data-config attribute

### PR DESCRIPTION
**Pull request by blag**
Please review this before accepting it, because I do not know of any implications of this change (it could just load the default configuration, or it could blow up).

The HTML for the CKEditor widget is:
<textarea class="django-ckeditor-textarea" cols="40" data-config-name="default" id="id_content" name="content" rows="10"></textarea>

The fix for this could be as simple as adding a data-config="<something>" attribute to the textarea, but I haven't done enough troubleshooting to figure out if that is a proper fix or not.

I'm not sure if I should include a data-config attribute on the textarea tag or not, but this got the widget loading for me.

### CODE REVIEW

**Comment by fdintino** [comment]
Perhaps I misunderstand what you are attempting to do, but it is possible to override the config variables of the default config (or the config specified in your django settings' CKEDITOR_CONFIG[config_name])
 by passing a dict of settings via the `extra_config` kwarg to RichTextField. This was a recent change and it is not described in the README, which is woefully out of date.

**Comment by fdintino** [comment]
It occurs to me that you might be experiencing problems if ckeditor.urls is not included in your urls.py. You need to have something like

``` python
urlpatterns = patterns('',
    # ...
    url(r'^ckeditor/', include('ckeditor.urls')),
    # ...
)
```

in your urls.py

**Comment by blag** [comment]
Thank you for your help. The ckeditor.urls is included in my urls.py appropriately as far as I can tell.

I'm not trying to do anything but get CKEditor to display and work in a form. The b=a.parseJSON(d.attr("data-config"))||{} section of code was throwing an exception and the editor was not loading. Putting the parseJSON call in a try/catch block and having the catch initialize b to an empty associative array "fixed" it. That's all I know.

**Comment by fdintino** [comment]
Okay, I think I see what the problem was. Try pulling down the latest version—I believe that fixes your issue.

**Comment by divadrei** [comment]
Hi, 
No it doesn't, still trying to do a JSON.parse(undefined), undefined is casted to string and you get a "SyntaxError: Unexpected token u"

You should replace

``` javascript
b = d.attr("data-config") || {}
```

by

``` javascript
b = d.attr("data-config") && a.parseJSON(d.attr("data-config")) || {}
```

or

``` javascript
b = d.data("config") && a.parseJSON(d.data("config")) || {}
```

**Comment by fdintino** [comment]
The non-minified version of this line is [here](https://github.com/theatlantic/ckeditor-dev/blob/atl/4.x/ckeditor_widget.js#L43)

What do you think about this, to fix it:

``` javascript
elementConfig = $.parseJSON($element.attr('data-config') || '{}') || {};
```

?

**Comment by divadrei** [comment]
I think it's ok, I don't really understand the interest of using a json parser for converting '{}' to an empty js object but it fixes the bug.
Thanks

_Thanks for the non minified version I was thinking "WTF is this obfuscated code in the repository" ;-)_

**Comment by fdintino** [comment]
Sorry for the excessive delay in getting this into our branch. Thanks for all your help.

**Pull request closed without merging**
