### PR TITLE
Be more forgiving to weird images. refs #3379

### PR DESCRIPTION
**Pull request by whatisjasongoldstein**
Seems to work locally (although I'm not set up to capture log events).

The idea here if it writers pass in an image that PIL doesn't like, it shouldn't break their whole workflow, but it also shouldn't pass silently in the event there's an edge case we should handle.

### CODE REVIEW

**Comment by Refefer** [comment]
Considering how important images are to Wire articles, I think having it hard stop when they upload one (or say a PSD) that isn't an image isn't a bad move. Furthermore, the naked Exception block catches a lot more than just bad image types, such as OutOfMemoryErrors, or disk mount errors and I think suppressing all of them is a little too aggressive.

**Comment by whatisjasongoldstein** [comment]
Some background:

Yesterday someone uploaded a post with 20+ photos in it. One of them, when hit with PIL .size() came back as (None, 500). Obviously, None width is no good, and resulted in a TypeError down the line.

I agree, errors like that should no pass silently, hence the logging. On the other hand, we had two writers who were trying to get stuff done, were getting 500 errors every time they saved, didn't know why, and once we told them it was a bad image, had no idea which one.

Yesterday, they had to remove and re-add every image individually until they figured out which broke it.

With this, that PSD would simply appear in their post as a busted image, and it would be very obvious that something is wrong with _this_ image. This is more meaningful to them - and to us, if they need to ask about it - than a big fat 500.

**Comment by whatisjasongoldstein** [comment]
And actually this only applies to resizes. If you try to upload an rtf or other ridiculous thing, it blows up just fine.

**Comment by joshmaker** [comment]
I agree, the worst case scenario is that the writer loses hours of work with no obvious way for them to recover it. The current 500 error also isn't helpful to the writer -- they don't know what they did that broke the CMS. The Sentry errors are helpful to us however, so we want to make sure we still receive them.

**Pull request closed without merging**
